# Numpy

## criando arrays com Numpy

In [10]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [12]:
import numpy as np

In [13]:
# criar um array com 10 elemento
my_array_1d = np.linspace(10, 100, 10)
my_array_1d

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [14]:
# acessar o ultimo elemento
print('ultimo elemento:', my_array_1d[-1])

# acessar do antepenultimo ao ultimo
print('antepenultimo ao ultimo elementoo:', my_array_1d[-3:])

# acessar o do primeiro ao 5° elemento (índice 4)
print('primeiro ao quinto elemento:', my_array_1d[:5])

ultimo elemento: 100.0
antepenultimo ao ultimo elementoo: [ 80.  90. 100.]
primeiro ao quinto elemento: [10. 20. 30. 40. 50.]


In [ ]:
np.linspace

In [ ]:
my_array_2d = np.linspace(10, 100, 10).reshape(2, 5)
my_array_2d

array([[ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.]])

In [ ]:
# acessar o 1° elemento da primeira linha
print(my_array_2d[0,0])


# acessar o 1° e 3° elemento da primeira linha
print(my_array_2d[0,:3])


# acessar o 1° elemento da primeira coluna
print(my_array_2d[:,0])


# acessar o 1° elemento da primeira coluna formatando o resultado como uma coluna
print(my_array_2d[:,[0]])

# acessar os elementos da 1° e 2° coluna das duas linhas
print(my_array_2d[:,:2])


10.0
[10. 20. 30.]
[10. 60.]
[[10.]
 [60.]]
[[10. 20.]
 [60. 70.]]


In [ ]:
# Dados de retornos diários de um ativo (em percentagem)
retornos = np.array([0.5, 1.2, -0.8, 0.7, -0.1, 1.0, -0.5])

# Calcular o desvio padrão dos retornos (volatilidade)
volatilidade = np.std(retornos)

print(f"A volatilidade dos retornos é: {volatilidade:.2f}%")

A volatilidade dos retornos é: 0.71%


## operações aritméticas

In [23]:
array_1 = np.ones((2,2))
array_2 = np.eye(2)
print('array 1:\n', array_1)
print('array 2:\n', array_2)

array 1:
 [[1. 1.]
 [1. 1.]]
array 2:
 [[1. 0.]
 [0. 1.]]


### soma

In [8]:
soma_array = array_1 + array_2
print('soma array 1 e 2:\n',soma_array)

# soma com broadcasting aplicado no array 1
print('broadcasting: somando o número 2 em todos elementos do array 1:\n', array_1 + 2)

soma array 1 e 2:
 [[2. 1.]
 [1. 2.]]
broadcasting: somando o número 2 em todos elementos do array 1:
 [[3. 3.]
 [3. 3.]]


### Subtração

In [10]:
subtracao_array = array_1 - array_2
print('subtração array 1 e 2:\n', subtracao_array)

# subtração com broadcasting aplicado no array 1
print('broadcasting: subtraindo o número 2 em todos elementos do array 1:\n', array_1 - 2)

subtração array 1 e 2:
 [[0. 1.]
 [1. 0.]]
broadcasting: subtraindo o número 2 em todos elementos do array 1:
 [[-1. -1.]
 [-1. -1.]]


### Divisão

In [11]:
divisao_array = array_1 / array_2
print('subtração array 1 e 2:\n', divisao_array)

# divisão com broadcasting aplicado no array 1
print('broadcasting: dividindo o número 2 em todos elementos do array 1:\n', array_1 / 2)

subtração array 1 e 2:
 [[ 1. inf]
 [inf  1.]]
broadcasting: dividindo o número 2 em todos elementos do array 1:
 [[0.5 0.5]
 [0.5 0.5]]


<ipython-input-11-87d856e33f63>:1: RuntimeWarning: divide by zero encountered in divide
  divisao_array = array_1 / array_2


### Observação do broadcasting

In [13]:
# Quando não funciona
np.array([1, 2, 3]) + np.array([1, 2]) # recebe um erro, pois o shape é inconsistente, o tamanho dos arrays são diferentes

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

[1]


### Multiplicação

In [15]:
multiplicacao_array = array_1 * array_2
print('subtração array 1 e 2:\n', multiplicacao_array)

# divisão com broadcasting aplicado no array 1
print('broadcasting: dividindo o número 2 em todos elementos do array 1:\n', array_1 * 2)

# outra maneira de criar array com a multiplacação em broadcasting
5 * np.ones((2,2))

subtração array 1 e 2:
 [[1. 0.]
 [0. 1.]]
broadcasting: dividindo o número 2 em todos elementos do array 1:
 [[2. 2.]
 [2. 2.]]


array([[5., 5.],
       [5., 5.]])

### Multiplicação matricial

In [24]:
# uso da função/método .dot ou @
print('multiplicação matricial usando np.dot\n', np.dot(array_1, array_2))
print('multiplicação matricial usando @\n', array_1 @ array_2)
print('multiplicação matricial usando método .dot\n', array_1.dot(array_2))

multiplicação matricial usando np.dot
 [[1. 1.]
 [1. 1.]]
multiplicação matricial usando @
 [[1. 1.]
 [1. 1.]]
multiplicação matricial usando método .dot
 [[1. 1.]
 [1. 1.]]


In [36]:
"""
Exemplo:
solução de sistema de equações:
   a + 2b = 7
  3a - 2b = -11
  Solução analítica: (a, b) = (-1, 4)
Matricialmente, este problema tem a seguinte forma:
  Ax = c, onde:
  x = [a, b]
  A = [[1, 2], [3, -2]]
  c = [7, -11]
  Solução numérica: x = inv(A) @ c
"""

A = np.array([[1, 2], [3, -2]])
c = np.array([[7], [-11]])
print('matriz A:\n', A)
print('vetor c:\n', c)

# solução
x = np.dot(np.linalg.inv(A), c)
# ou poderia ser usado: x = np.linalg.inv(A) @ c
print('solução do sistema de equações:\n', x)
print('\n(a,b):\n', x.ravel())

matriz A:
 [[ 1  2]
 [ 3 -2]]
vetor c:
 [[  7]
 [-11]]
solução do sistema de equações:
 [[-1.]
 [ 4.]]

(a,b):
 [-1.  4.]
